version: "3.8"
services:
  web:
    image: brettt89/silverstripe-web:8.1-apache
    container_name: stripe_web
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - SS_TRUSTED_PROXY_IPS=*
      - SS_ENVIRONMENT_TYPE=dev
      - SS_DATABASE_SERVER=db
      - SS_DATABASE_NAME=stripe
      - SS_DATABASE_USERNAME=root
      - SS_DATABASE_PASSWORD=root
      - SS_DEFAULT_ADMIN_USERNAME=admin
      - SS_DEFAULT_ADMIN_PASSWORD=password
      - uid=$(id -u)
    user: '1000'
    ports:
      - 80:80
  db:
    image: mariadb:10.2
    container_name: stripe_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer_concens
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
     db-data:
